moneybags/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import TemplateView


# /new/
# /<account_slug>/update/
# /<account_slug>/new/
# /<account_slug>/report/
# /<account_slug>/transaction/<transaction_id>/
# /<account_slug>/recurring/<transaction_id>/
# /<account_slug>/<transaction_id>/
# /<account_slug>/
# /accounts/
# /saved/
# /

urlpatterns = patterns('moneybags.views',
    url(r'^new/$',
        'create_account',
        name='moneybags-create-account'),

    url(r'^accounts/$',
        'list_accounts',
        name='moneybags-list-accounts'),

    url(r'^(?P<account_slug>.*)/update/$',
        'update_transactions',
        name='moneybags-update-transactions'),

    url(r'^(?P<account_slug>.*)/new/$',
        'create_transaction',
        name='moneybags-create-transaction'),

    url(r'^(?P<account_slug>.*)/report/$',
        'transaction_report',
        name='moneybags-transaction-report'),

    url(r'^(?P<account_slug>.*)/transaction/(?P<transaction_id>\d+)/$',
        'detail_transaction',
        name='moneybags-detail-transaction'),

    url(r'^(?P<account_slug>.*)/recurring/(?P<recurring_transaction_id>\d+)/$',
        'update_recurring_transaction',
        name='moneybags-update-recurring-transaction'),

    url(r'^(?P<account_slug>.*)/(?P<transaction_id>\d+)/$',
        'recurring_transaction',
        name='moneybags-recurring-transaction'),

    url(r'^(?P<account_slug>.*)/$',
        'detail_account',
        name='moneybags-detail-account'),
)

urlpatterns += patterns('',
    url(r'^saved/$',
        TemplateView.as_view(template_name='moneybags/saved.html'),
        name='moneybags-saved'
    ),
    url(r'^$',
        TemplateView.as_view(template_name='moneybags/default.html'),
        name='moneybags-default'
    ),
)

moneybags/models.py
import datetime

from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify

from .settings import (
    AMOUNT_DECIMAL_PLACES,
    AMOUNT_MAX_DIGITS,
    TRANSACTION_TYPE_DEBIT,
    TRANSACTION_TYPE_CREDIT,
)

User = get_user_model()


class Account(models.Model):
    """A named container for Transactions, and is owned by a ``User``."""
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, db_index=True)
    owner = models.ForeignKey(User)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name', ]
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'

    def save(self, *args, **kwargs):
        """ Generate the slug from the name """
        self.slug = slugify(self.name)
        super(Account, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('moneybags-detail-account', args=[self.slug])

    def _get_debits(self):
        """return the sum of all debits for this account"""
        debits = self.transaction_set.filter(transaction_type=-1)
        debits = debits.values_list('amount', flat=True)
        return sum(list(debits))

    def _get_credits(self):
        """ return the sum of all credits for this account"""
        credits = self.transaction_set.filter(transaction_type=1)
        credits = credits.values_list('amount', flat=True)
        return sum(list(credits))

    def get_balance(self):
        credits = self._get_credits()
        debits = self._get_debits()
        return credits - debits


class TransactionManager(models.Manager):

    def debits(self):
        return self.filter(transaction_type=-1)

    def credits(self):
        return self.filter(transaction_type=1)

    # TODO: put in aggregate functions here that accept account as input, and
    #       give us the balance, total debits, total credits?


class Transaction(models.Model):
    """This class represents a monetary transaction."""
    TRANSACTION_TYPE = (
        (TRANSACTION_TYPE_CREDIT, 'Credit'),
        (TRANSACTION_TYPE_DEBIT, 'Debit'),
    )
    account = models.ForeignKey(Account)
    date = models.DateField(db_index=True,
        help_text="The Date of this transaction")
    check_no = models.PositiveIntegerField(blank=True, null=True,
        help_text="Optional: Check Number")
    description = models.CharField(max_length=255, db_index=True,
        help_text="Description for this Transaction")
    amount = models.DecimalField(max_digits=AMOUNT_MAX_DIGITS,
        decimal_places=AMOUNT_DECIMAL_PLACES,
        help_text="Amount of this Transaction")
    recurring = models.BooleanField(blank=True, default=False, db_index=True,
        help_text="Is this a Recurring Transaction")
    pending = models.BooleanField(blank=True, default=True, db_index=True,
        help_text="Is this transaction still pending?")
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE,
        db_index=True, help_text="The Type of Transaction")
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "{0} on {1}: {2}".format(
            self.description,
            self.date,
            self.amount
        )

    class Meta:
        ordering = ['-date', 'check_no', 'description']
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transaction'

    def get_absolute_url(self):
        args = [self.account.slug, self.id]
        return reverse('moneybags-detail-transaction', args=args)

    def get_recurring_transaction_url(self):
        args = [self.account.slug, self.id]
        return reverse('moneybags-recurring-transaction', args=args)

    def save(self, *args, **kwargs):
        """
        Before saving an object, we set the sign of the amount based on the
        transaction type. We then create or update a RecurringTransaction
        if neccessary.
        """
        super(Transaction, self).save(*args, **kwargs)
        self._create_or_update_recurring_transaction()

    def _create_or_update_recurring_transaction(self):
        """
        If this transaction is recurring, this method will fetch the
        corresponding ``RecurringTransaction`` object, if it exists. If the
        ``RecurringTrasaction`` object does not exist, it will be created.

        In either case, the ``RecurringTransaction`` instance is updated with
        values from this ``Transaction``.

        This method returns a tuple containing 2 objects:

        1. An instance of ``RecurringTransaction``
        2. A boolean value indicating whether or not the object was created
        """
        if self.recurring:
            desc_slug = slugify(self.description)
            try:
                rt = RecurringTransaction.objects.get(
                    desc_slug=desc_slug,
                    account=self.account,
                    transaction_type=self.transaction_type
                )
            except RecurringTransaction.DoesNotExist:
                rt = RecurringTransaction(
                    desc_slug=desc_slug,
                    account=self.account,
                    transaction_type=self.transaction_type
                )
                rt.frequency_start_date = self.date

            rt.description = self.description
            rt.amount = self.amount
            rt.last_transaction_date = self.date
            rt.save()

    def is_credit(self):
        return self.transaction_type > 0

    def abs_amount(self):
        return abs(self.amount)

    def get_recurring_transaction(self):
        rt = None
        if self.recurring:
            try:
                rt = RecurringTransaction.objects.get(
                    desc_slug=slugify(self.description),
                    account=self.account,
                    transaction_type=self.transaction_type
                )
            except RecurringTransaction.DoesNotExist:
                # Ugh... create it?
                rt = RecurringTransaction(
                    desc_slug=slugify(self.description),
                    account=self.account,
                    transaction_type=self.transaction_type
                )
                rt.description = self.description
                rt.amount = self.amount
                rt.last_transaction_date = self.date
                rt.frequency_start_date = self.date
                rt.save()

        return rt

    def get_similar_transactions(self):
        transactions = Transaction.objects.filter(
            description=self.description,
            transaction_type=self.transaction_type,
            account=self.account
        )
        transactions = transactions.exclude(id=self.id)
        return transactions

    admin_objects = models.Manager()
    objects = TransactionManager()


class RecurringTransactionManager(models.Manager):
    def due_today(self):
        return self.filter(due_date=datetime.date.today())


class RecurringTransaction(models.Model):
    """This model provides a way to track recurring transactions. Note
    that the ``desc_slug`` and ``account`` fields are set as
    ``unique_together``.

    One instance of this model will represent the "last" time a recurring
    transaction was made.

    """
    FREQUENCY_CHOICES = (
        ('d', 'Daily'),
        ('w', 'Weekly'),
        ('b', 'Bi-Weekly'),
        ('m', 'Monthly'),
        ('y', 'Yearly'),
        ('q', 'Quarterly'),
    )
    description = models.CharField(max_length=255,
        help_text="This should match the description from the Transaction")
    desc_slug = models.SlugField(max_length=255,
        help_text="A sluggified version of the description")
    amount = models.DecimalField(max_digits=AMOUNT_MAX_DIGITS,
        decimal_places=AMOUNT_DECIMAL_PLACES,
        help_text="Amount to be paid")
    account = models.ForeignKey(Account,
        help_text="The Account in which this belongs")
    frequency = models.CharField(max_length=1, choices=FREQUENCY_CHOICES)
    frequency_start_date = models.DateField(
        help_text="The date from which the frequency should be calculated")
    last_transaction_date = models.DateField(
        help_text="The date on which the last transaction occurred")
    transaction_type = models.IntegerField(
        choices=Transaction.TRANSACTION_TYPE,
        help_text="The Type of Transaction")
    due_date = models.DateField(help_text="Automatically Generated from the "
        "Frequency and Frequency Start Date")
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u"{0}: {1} - last transaction date {2}".format(
            self.account.name,
            self.description,
            self.last_transaction_date
        )

    class Meta:
        ordering = [
            'account', '-last_transaction_date', 'transaction_type',
            'description'
        ]
        unique_together = ['account', 'desc_slug']

    def get_absolute_url(self):
        return self.account.get_absolute_url()

    def get_edit_url(self):
        args = [self.account.slug, self.id]
        return reverse('moneybags-update-recurring-transaction', args=args)

    def save(self, *args, **kwargs):
        """Just ``slugify`` the Description."""
        self.desc_slug = slugify(self.description)
        self.due_date = self.get_due_date() or self.frequency_start_date or \
            self.last_transaction_date
        super(RecurringTransaction, self).save(*args, **kwargs)

    def get_type(self):
        """credit if amount > 0, debit otherwise """
        if self.transaction_type > 0:
            return 'credit'
        return 'debit'

    def get_due_date(self):
        """ Calculate the due date for this recurring transaction """
        new_date = None
        prev_date = max(self.frequency_start_date, self.last_transaction_date)
        if self.frequency == 'd':

moneybags/templates/moneybags/_nav.html
{% load url from future %}
<a class="brand" href="{% url 'moneybags-default' %}">Moneybags</a>
<div class="nav-collapse collapse">
<ul class="nav">
  <li><a href="{% url 'moneybags-create-account' %}">Create Account</a></li>
  <li><a href="{% url 'moneybags-list-accounts' %}">List Accounts</a></li>
  {% if account.slug %}
    <li><a href="{% url 'moneybags-transaction-report' account.slug %}">
    Reporting</a></li>
  {% endif %}
</ul>
</div><!--/.nav-collapse -->

moneybags/templates/moneybags/account_create.html
{% extends "moneybags/base.html" %}
{% load url from future %}

{% block content %}
    <h2>Create an Account</h2>
    {% if form %}
    <form action="{% url 'moneybags-account-create' %}" method="post">{% csrf_token %}
    <fieldset><legend>New Account</legend>
    <ul>
    {{ form.as_ul }}
    <li class="submitbutton"><input type="submit" value="Create Account"/></li>
    </ul>
    </fieldset>
    </form>
    {% endif %}
{% endblock %}

moneybags/templates/moneybags/account_list.html
{% extends "moneybags/base.html" %}
{% load url from future %}

{% block content %}
    <h2>Accounts</h2>
    <p>&rarr; <a href="{% url 'moneybags-account-create' %}">Create an Account</a></p>
    {% if accounts %}
        <table>
        <caption>Accounts &amp; Balances</caption>
        <thead>
            <tr>
            <th>Account</th>
            <th>Balance</th>
            </tr>
        </thead>
        <tbody>
        {% for account in accounts %}
            <tr>
            <td><a href="{{ account.get_absolute_url }}">{{ account }}</a></td>
            <td>{{ account.get_balance }}</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% else %}
        <p>You haven't set up any Accounts yet.  <a href="{% url 'moneybags-account-create' %}">Create One</a>!</p>
    {% endif %}

{% endblock %}

moneybags/templates/moneybags/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{% block title %}Moneybags!{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet">
<style type="text/css">
/* 60px to make the container go all the way to the bottom of the topbar */
body {padding-top: 60px;}
table > tbody > tr > th {width: 20%;}
table > caption {text-align: left; margin: 20px 0 0 0; padding:0;}
canvas {padding:0; margin:0 auto;}
</style>
<link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
{% block extrahead %}{% endblock %}
</head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% include "moneybags/_nav.html" %}
        </div>
      </div>
    </div>

    <div class="container">
    {% block content %}{% endblock %}
    </div> <!-- /container -->

<!-- JS Placed at the end of the document so the pages load faster -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
{% block endbody %}{% endblock %}
</body>
</html>

moneybags/templates/moneybags/coffer_create.html
{% extends "base.html" %}

{% block content %}
    <h2>Create an Coffer</h2>
    {% if form %}
    <form action="{% url moneybags-coffer-create %}" method="post">{% csrf_token %}
    <fieldset><legend>New Coffer</legend>
    <ul>
    {{ form.as_ul }}
    <li class="submitbutton"><input type="submit" value="Create Coffer"/></li>
    </ul>
    </fieldset>
    </form>
    {% endif %}
{% endblock %}

moneybags/templates/moneybags/create_account.html
{% extends "moneybags/base.html" %}
{% load url from future %}
{% load bootstrap_tags %}

{% block content %}
    <h1>Create Account</h1>

    {% if form %}
    <form action="{% url 'moneybags-create-account' %}"
          method="post" class="form-horizontal">{% csrf_token %}
    <fieldset><legend>New Account</legend>
        {{ form|as_bootstrap }}
        <div class="form-actions">
        <input type="submit" class="btn btn-primary" value="Create Account"/>
        </div>
    </fieldset>
    </form>
    {% endif %}
{% endblock %}

moneybags/templates/moneybags/create_transaction.html
{% extends "moneybags/base.html" %}
{% load url from future %}
{% load bootstrap_tags %}

{% block content %}
    <h1>{{ account }} <small>New Transaction</small></h1>

    {% if form %}
    <form action="{% url 'moneybags-create-transaction' account.slug %}"
          method="post" class="form-horizontal">{% csrf_token %}
    <fieldset><legend>New Transaction</legend>
        {{ form|as_bootstrap }}
        <div class="form-actions">
        <input type="submit" class="btn btn-primary" value="Save"/>
        </div>
    </fieldset>
    </form>
    {% endif %}
{% endblock %}

moneybags/templates/moneybags/detail_account.html
{% extends "moneybags/base.html" %}
{% load url from future %}

{% block content %}

    <h1>{{ account }} <small id="balance"
        class="{% if overdrawn %}text-error{% else %}text-info{% endif %}">
        Balance: $ {{ balance|floatformat:2 }}</small>
    </h1>

    <div class="clearfix">
    <a href="{% url 'moneybags-create-transaction' account.slug %}"
       class="pull-right btn btn-primary">New Transaction</a>
    </div>
    {% if recurring_transactions %}
        <table class="table tabled-border">
        <caption class="lead">Upcoming Recurring Transactions</caption>
        <thead>
            <tr>
            <th class="type">Type</th>
            <th class="date">Due</th>
            <th class="freq">Frequency</th>
            <th class="description">Description</th>
            <th class="amount">Amount</th>
            </tr>
        </thead>
        <tbody>
        {% for rt in recurring_transactions %}
            {% with t=rt.get_type %}
            <tr class="{% if t == "credit" %}success{% elif t == "debit" %}error{% endif %}
                       {{ type }}">
            <td>
                {% if t == "credit" %}
                    <span class="label label-success">Credit</span>
                {% elif t == "debit" %}
                    <span class="label label-important">Debit</span>
                {% else %}
                    <span class="label">unknown</span>
                {% endif %}
            </td>
            <td>{{ rt.due_date|date:"M j, Y" }}</td>
            <td>{{ rt.get_frequency_display }}</td>
            <td><a href="{{ rt.get_edit_url }}">{{ rt.description }}</a></td>
            <td><strong>{{ rt.amount|floatformat:2 }}</strong></td>
            </tr>
            {% endwith %}
        {% endfor %}
        </tbody>
        </table>
        <hr/>
    {% endif %}


    {% if transactions %}
        <form action="{% url 'moneybags-update-transactions' account.slug %}"
              method="post">{% csrf_token %}
        {{ formset.management_form }}
        <table class="table table-striped">
        <caption class="lead">Recent Transactions</caption>
        <thead>
            <tr>
            <th>&nbsp;</th>
            <th class="type">Type</th>
            <th class="date">Date</th>
            <th class="ckno"><abbr title="Check Number">Ck no.</abbr></th>
            <th class="description">Description</th>
            <th class="amount">Amount</th>
            </tr>

            {% comment %}
            <tr>
            <td class="selectall"></td>
            <td colspan="5">
            <button type="submit" id="id_remove_pending" name="action" value="remove-pending" class="btn">Remove Pending</button>
            <button type="submit" id="id_delete" name="action" value="delete" class="btn">Delete</button>
            </td>
            </tr>
            {% endcomment %}
        </thead>

        <tfoot>
            <tr>
            <td class="selectall"></td>
            <td colspan="5">
            <button type="submit" id="id_remove_pending" name="action"
                    value="remove-pending" class="btn btn-info">Remove Pending</button>
            <button type="submit" id="id_delete" name="action" value="delete"
                    class="btn btn-danger">Delete</button>
            </td>
            </tr>
        </tfoot>

        <tbody>
        {% for t in transactions %}
            <tr class="transaction {% if t.is_credit %}credit{% else %}debit{% endif %}
            {% if t.recurring %}recurring{% endif %} {% if t.pending %}pending muted{% endif %}">

            {# Checkbox from the formset #}
            <td>
                {% for form in formset.forms %}
                    {% ifequal form.initial.object_id t.id %}
                        {% for field in form %}
                            {{ field }}
                        {% endfor %}
                    {% endifequal %}
                {% endfor %}
            </td>

            {# Transaction Type #}
            <td>
                {% if t.is_credit %}
                    <span class="label label-success">Credit</span>
                {% else %}
                    <span class="label label-important">Debit</span>
                {% endif %}
                {% if t.recurring %}
                    <span class="label label-info">Recurring</span>
                {% endif %}
                {% if t.pending %}
                    <span class="label">Pending</span>
                {% endif %}
            </td>

            {# Transaction Date #}
            <td>
                {{ t.date|date:"M j, Y" }}
            </td>

            {# Check number if appropriate #}
            <td>
                {% if t.check_no %}{{ t.check_no }}{% else %}{% endif %}
            </td>

            {# Description #}
            <td>
                <a href="{{ t.get_absolute_url }}">{{ t.description }}</a>
            </td>

            {# Amount #}
            <td>
                {% if t.is_credit %}
                    ({{ t.amount|floatformat:2 }})
                {% else %}
                    {{ t.abs_amount|floatformat:2 }}
                {% endif %}
            </td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
        </form>

        {# ---------------- Pagination ----------------------- #}
        <div class="pagination pagination-centered">
        <ul>
        {% if transactions.has_previous %}
            <li><a href="?page={{transactions.previous_page_number}}">Prev</a></li>
        {% else %}
            <li class="disabled"><a name="Prev">Prev</a></li>
        {% endif %}

        {% if transactions.paginator.num_pages > 25 %}
          {% with page_range=transactions.paginator.page_range %}
            {# Links to the first 10 pages ... #}
            {% for p in page_range|slice:":10" %}
                <li><a{% if p == transactions.number %} class="active"{% endif %}
                      href="?page={{ p }}">{{ p }}</a></li>
            {% endfor %}
            <li class="disabled"><a name="...">...</a></li>
            {# Links to the last 5 pages. #}
            {% for p in page_range|slice:"-5:" %}
                <li><a{% if p == transactions.number %} class="active"{% endif %}
                      href="?page={{ p }}">{{ p }}</a></li>
            {% endfor %}
          {% endwith %}
        {% else %}
          {% for p in transactions.paginator.page_range %}
              <li><a{% if p == transactions.number %} class="active"{% endif %}
                    href="?page={{ p }}">{{ p }}</a></li>
          {% endfor %}
        {% endif %}

        {% if transactions.has_next %}
            <li><a href="?page={{transactions.next_page_number}}">Next</a></li>
        {% else %}
            <li class="disabled"><a name="Next">Next</a></li>
        {% endif %}
        </ul>
        </div>
        {# ------------- End Pagination ----------------------- #}

    {% else %}
        {% if balance %}
            {# There have been *some* transactions, just not recently #}
            <p>You don't have any recent transactions.</p>
        {% else %}
            <p>You currently have no transactions.</p>
        {% endif %}
    {% endif %}
{% endblock %}

moneybags/templates/moneybags/detail_transaction.html
{% extends "moneybags/base.html" %}

{% block content %}

    <h1>{{ account.name }} <small>Transaction Details</small></h1>

    <ul class="breadcrumb">
    <li>
        <a href="{{ account.get_absolute_url }}">{{ account.name }}</a>
        <span class="divider">/</span>
    </li>
    <li class="active">{{ transaction.description }}</li>
    </ul>

    <table class="table table-bordered table-hover">
    <tbody>
        {# Transaction Date #}
        <tr>
            <th>Date</th>
            <td>{{ transaction.date|date:"M j, Y" }}</td>
        </tr>

        {# Check number (if available) #}
        {% if transaction.check_no %}
        <tr>
            <th>Check Number</th>
            <td>{{ transaction.check_no }}</td>
        </tr>{% endif %}

        {# Amount #}
        <tr>
            <th>Amount</th>
            <td>$ {{ transaction.amount|floatformat:2 }}</td>
        </tr>

        {# Transaction Type #}
        <tr>
            <th>Type:</th>
            <td>
            {% with t=transaction.get_transaction_type_display %}
                {% if t == "Credit" %}
                    <span class="label label-success">Credit</span>
                {% elif t == "Debit" %}
                    <span class="label label-important">Debit</span>
                {% else %}
                    <span class="label">unknown</span>
                {% endif %}
            {% endwith %}
            </td>
        </tr>

        {# Pending Status #}
        <tr><th>Pending</th><td>{{ transaction.pending|yesno }}</td></tr>

        {# Recurring Status #}
        <tr><th>Recurring</th><td>{{ transaction.recurring|yesno }}</td></tr>

        {# Updated #}
        <tr>
            <th>Last Updated</th>
            <td>{{ transaction.updated_on|date:"M j, Y | g:ia" }}</td>
        </tr>
    </tbody>
    </table>

    {% if similar_transactions %}

        <table class="table table-striped table-condensed">
        <caption class="lead">Similar Transactions
          {% if similar_transactions|length > 5 %}
          {# chart of similar transactions #}
          <canvas id="similar_chart" width="940" height="100"></canvas>
          {% endif %}
        </caption>
        <thead>
            <tr>
            <th>Date</th>
            <th>Check No</th>
            <th>Amount</th>
            <th>Updated On</th>
            </tr>
        </thead>
        <tbody>
        {% for t in similar_transactions %}
            <tr{% if t.pending %} class="muted"{% endif %}>
            <td>{{ t.date|date:"M j, Y" }}</td>
            <td>{{ t.check_no|default:"&mdash;" }}</td>
            <td>$ {{ t.amount|floatformat:2 }}</td>
            <td>{{ t.updated_on|date:"M j, Y | g:ia" }}</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% endif %}
{% endblock %}


{% block endbody %}
{% if similar_transactions|length > 5 %}
<script type="text/javascript" src="{{ STATIC_URL }}chart/Chart.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  var ctx = $("#similar_chart").get(0).getContext("2d");
  var chart = new Chart(ctx);
  var data = {
	  labels : [{% for t in similar_transactions %}"{{t.date|date:"Y-m-d"}}-{{t.id}}"{% if not forloop.last %},{% endif %}{% endfor %}],
    datasets : [
      {
        fillColor : "rgba(151,187,205,0.5)",
        strokeColor : "rgba(151,187,205,1)",
        pointColor : "rgba(151,187,205,1)",
        pointStrokeColor : "#fff",
        data : [{% for t in similar_transactions %}{{t.amount}}{% if not forloop.last %},{% endif %}{% endfor %}]
      }
    ]
  }
  options = {
    scaleLineColor : "#fff", // same as background == invisible
    scaleLineWidth: 1, // Small Scale line
    scaleShowLabels : false, // Don't show labels on the scale
    scaleShowGridLines : false, // Don't show grid lines
    pointDot : false, // Don't show a dot for each point
  }
  chart.Line(data, options);
});
</script>
{% endif %}
{% endblock %}

moneybags/templates/moneybags/saved.html
{% extends "moneybags/base.html" %}

{% block content %}
    <p class="success">Your content has been saved!</p>
{% endblock %}

moneybags/templates/moneybags/transaction_detail.html
{% extends "moneybags/base.html" %}

{% block content %}

    <h2><a href="{{ account.get_absolute_url }}">{{ account.name }}</a></h2>
    <table class="transactiondetail">
    <caption>{{ transaction.description }}</caption>
    <tbody>
    <tr><th>Date</th><td>{{ transaction.date|date:"M j, Y" }}</td></tr>
    {% if transaction.check_no %}<tr><th>Check Number</th><td>{{ transaction.check_no }}</td></tr>{% endif %}
    <tr class="alternate"><th>Amount</th><td>{{ transaction.amount }}</td></tr>
    <tr><th>Type:</th><td>{{ transaction.get_transaction_type_display }}</td></tr>
    <tr class="alternate"><th>Pending</th><td>{{ transaction.pending|yesno }}</td></tr>
    <tr><th>Recurring</th><td>{{ transaction.recurring|yesno }}</td></tr>
    <tr class="alternate"><th>Last Updated</th><td>{{ transaction.updated_on|date:"M j, Y g:ia" }}</td></tr>
    </tbody>
    </table>

    {% if similar_transactions %}
        <table>
        <caption>Similar Transactions</caption>
        <thead>
            <tr>
            <th>Date</th>
            <th>Check No</th>
            <th>Amount</th>
            <th>Updated On</th>
            </tr>
        </thead>
        <tbody>
        {% for t in similar_transactions %}
            <tr class="transaction{% if t.pending %} pending{% endif %}{% cycle '' ' alternate'%}">
            <td>{{ t.date|date:"Y-m-d" }}</td>
            <td>{% if t.check_no %}{{ t.check_no }}{% else %}n/a{% endif %}</td>
            <td>{{ t.amount }}</td>
            <td>{{ t.updated_on|date:"Y-m-d g:ia" }}</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% endif %}
{% endblock %}